name: Build Docker image
on:
  push:
    branches:
      - 'master'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        working-directory: docker
        run: docker-compose build
      -
        name: Push image
        working-directory: docker
        run: docker-compose push
